package boot.dynamodb.model;

import boot.dynamodb.util.TableNameResolver;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.io.Serializable;
import java.util.Objects;

@TableNameResolver("dynamodb.table.name.comment")
@DynamoDBTable(tableName = "THIS_SHOULD_BE_REPLACED_FROM_PROPERTY_FILE")
public class Comment implements Serializable {

    private String id;
    private String userId;
    private String comment;
    private String timestamp;
    private String collectionId;
    private String assetId;

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getUserId() {
        return userId;
    }

    @DynamoDBAttribute
    public String getComment() {
        return comment;
    }

    @DynamoDBAttribute
    public String getTimestamp() {
        return timestamp;
    }

    @DynamoDBAttribute
    public String getCollectionId() {
        return collectionId;
    }

    @DynamoDBAttribute
    public String getAssetId() {
        return assetId;
    }

    @Override
    public String toString() {
        return "Comment{id='" + id + '\''
                + ", userId='" + userId + '\''
                + ", comment='" + comment + '\''
                + ", timestamp='" + timestamp + '\''
                + ", collectionId='" + collectionId + '\''
                + ", assetId='" + assetId + '\''
                + '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Comment comment1 = (Comment) o;
        return Objects.equals(getId(), comment1.getId())
                && Objects.equals(getUserId(), comment1.getUserId())
                && Objects.equals(getComment(), comment1.getComment())
                && Objects.equals(getTimestamp(), comment1.getTimestamp())
                && Objects.equals(getCollectionId(), comment1.getCollectionId())
                && Objects.equals(getAssetId(), comment1.getAssetId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(), getUserId(), getComment(), getTimestamp(), getCollectionId(), getAssetId());
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    public void setCollectionId(String collectionId) {
        this.collectionId = collectionId;
    }

    public void setAssetId(String assetId) {
        this.assetId = assetId;
    }
}
